- name: homebrew の cask-fonts リポジトリを追加
  homebrew_tap: tap=homebrew/cask-fonts state=present
- name: フォントをインストール
  homebrew_cask:
    name: "{{ item }}"
    state: latest
  with_items:
    - font-noto-mono
    - font-noto-sans-mono
    - font-noto-sans-cjk-jp
    - font-source-han-mono
